### ISSUE TITLE
Please add support for regular usename/password authentication

### ISSUE THREAD

**Issue by fberasategui** [microsoft/PowerPlatform-CdsServiceClient#12]
Or provide a clear, easy to follow migration path to use any other auth mechanism for external applications.

**Comment by MattB-msft** [comment]
We are considering adding AD support only at this time.  Timeline is TBD as we are working on the MSAL port right now.   In general User /PW flows for Non-Interactive connections will be blocked by Azure Active Directory Policies over the next year or 2.. currently all new tenants being created cannot use UID/PW non interactive flows. . 

We will not be adding in any of the WS-TRUST support we had in the prior lib as that path is being retried, along with the OrganziationServiceProxy class.

**Comment by MattB-msft** [comment]
Please see : https://docs.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-common-data-service
