### ISSUE TITLE
Discussion: Open Source the CDS SDK

### ISSUE THREAD

**Issue by fberasategui** [microsoft/PowerPlatform-CdsServiceClient#14]
Is there any reason that the external, user-facing bits of CDS code remain closed-source?

Instead of complaining and raising issues and expecting the CDS team to fix them, we the people could contribute to the SDK ourselves. I have a TON of improvements and suggestions I'd like to pull request here, and the skills required to write proper code that *could* potentially be taken seriously.

**Comment by MattB-msft** [comment]
It is our intent to expose parts of our SDK, including the CdsServiceClient, on git Hub,  however those aspects that are part of our server we will continue to keep closed. 

This is being done over time with the CdsServiceClient being the first one that will be exposed this way.   Insofar as taking contributions, the initial effort we will be providing the code for view and comment, in the case of the CdsServiceClient, it will not be able to be compiled outside of our internal servers,  
While we will not be able to directly take PR's though we can certainly look over them and use them to influence the development going forward.
