### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by jordimontana82** [microsoft/PowerPlatform-CdsServiceClient#16]
No harm  on having one I guess ;) 

@MattB-msft

**Comment by MattB-msft** [comment]
Code of conduct is present in the project Jordi.. 
its linked on In the ReadMe under contributing 
https://opensource.microsoft.com/codeofconduct/

**Comment by jordimontana82** [comment]
Sorry, normally it's a .md file in repos but yeah I didn't see that, thanks!
