### ISSUE TITLE
Using CdsServiceClient with connection string, on prem, IFD

### ISSUE THREAD

**Issue by larrywelch** [microsoft/PowerPlatform-CdsServiceClient#17]
I'm attempting to use the CdsServiceClient.  I'm providing a connection string.  I get a client but the IsReady is always false.  There is no information in the client object telling what is wrong.  

Here's my connection string (parameter details are represented with xxxx):
Url = https://xxxxxx.com/xxxxxx; Domain = xxxxxx; AuthType = IFD; UserName = xxx.xxx@xxxxxx.com; Password = XXXXXX; RequireNewInstance = True

Any help will be greatly appreciated!

**Comment by MattB-msft** [comment]
@larrywelch 
WS-TRUST based flows are not supported going foward in this lib. 
In the ReadMe on the first page: 

- We are supporting only Client Secret / Cert flows for .net core. On .net framework additionally we support OAuth User flows
- We are shipping the initial drop using ADAL.net for the Auth Lib. We MAY change to use MSAL shortly
- MSAL would enabled us to support User Interactive flows on .net core. 

In the case of IFD, if your on ADFS from Windows 2016+ you can enabled OAuth and register a client ID to be used for user flows and Application flows.   

Regarding the authflow your trying here,  That is a noninteractive userpassword flow,  that wont be supported by the lib going forward based on the overall direction the auth stack's are taking in Microsoft. 

The preferred way that you would do that going forward would be to use a Service Principal, registered in ADFS, with client secret or certificate auth.  

Please take a look here too: [Deprecation of Office365 authentication type and OrganizationServiceProxy class for connecting to Common Data Service](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-common-data-service) 

if you need to continue to use UserID / Password Noninteractive flows, you can stay with CrmServiceClient for a while yet. 

thanks
