### ISSUE TITLE
New T-SQL endpoint

### ISSUE THREAD

**Issue by jordimontana82** [microsoft/PowerPlatform-CdsServiceClient#18]
Just wondering about the new insane amazing t-sql endpoint :) 

Will the new t-sql endpoint have a specific api in this repo? But I'm guessing is just "No", if the intent is to just use plain Entity Framework / EF Core to connect to it and run queries? 

Are there or there will be any known limits in the endpoint like we have currently with the LINQ provider in the SDK when it translates to QueryExpression (i.e. number of joins, left outer joins and combination of these)?

If there are some bits that translate T-SQL into FetchXml / QueryExpression, would be possible to open source those bits only? :D 

Thanks a mill!

**Comment by MattB-msft** [comment]
Glad your looking forward to it,  and no it will not appear here as its purely a server side implementation. 

The focus of this initial effort is around general query support using the T-SQL language spec,  Right now its design will allow for considerably more complex queries than we support in QE or Fetch,  as we are bypassing some of that layer to make this work. 
In general for client dev, it We expect that it will work along side this lib ( for now ) where you would use this lib/crmserviceclient/webapi to Create / Update / Delete / CustomActions and the SQL endpoint to do retrieves.   

We will talk more about this publicly and get a bit more doc's out there in the near future.

**Comment by jordimontana82** [comment]
Cool, thanks @MattB-msft !
