### ISSUE TITLE
System.DllNotFoundException : Unable to load shared library 'Rpcrt4' on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by jordimontana82** [microsoft/PowerPlatform-CdsServiceClient#2]
Hi! Amazing work on this new nuget package!

I've only come across this error which is thrown on linux (Ubuntu 18.04) when trying to call .SaveChanges() straight after a .AddObject(). Same code works fine on a Windows 10 machine.

            
           //service here implements IOrganizationService
            using (var ctx = new XrmServiceContext(service))
            {
                ctx.AddObject(new Account() { Name = "Test account" });
                ctx.SaveChanges();

                var account = ctx.CreateQuery<Account>()
                            .ToList()
                            .FirstOrDefault();
            }

System.DllNotFoundException : Unable to load shared library 'Rpcrt4' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libRpcrt4: cannot open shared object file: No such file or directory Stack Trace: at Microsoft.Xrm.Sdk.Client.NativeMethods.UuidCreateSequential(Guid& ptrGuid) at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.CreateSequentialGuid() at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SetNewId(Entity entity) at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.TraverseEntityGraph(Entity entity, Action1 onEntity, Action3 onLink, IEnumerable1 path)+MoveNext() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source) at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.GetSaveChangesResult(SaveChangesResultCollection results, Entity entity) at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.GetChangeRequestsFromChangedTree(SaveChangesResultCollection results, Entity entity, IEnumerable1 path, IList1 circularLinks)+MoveNext() at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.GetChangeRequests(SaveChangesResultCollection results, Entity entity)+MoveNext() at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChanges(SaveChangesOptions options) at Microsoft.Xrm.Sdk.Client.OrganizationServiceContext.SaveChanges()

**Comment by MattB-msft** [comment]
Thanks for the report,  We have identified the issue in an underlying library we are using and are working on a fix for it now.

**Comment by MattB-msft** [comment]
We have pushed the fix for this into the 0.0.1.11-Alpha nuget package that is deploying now,  Please do check the release notes as we also updated a number of discovery related operations.,

**Comment by jordimontana82** [comment]
@MattB-msft  Awesome! I've tried now and it works perfectly with a few tests I had. Thanks a mill
