### ISSUE TITLE
Microsoft.OData.ODataException: Cannot convert a value to target type 'Edm.Decimal'

### ISSUE THREAD

**Issue by ryanspain** [microsoft/PowerPlatform-CdsServiceClient#26]
Hi there,

First of all - Great work on the new SDK - I love using it throughout my non-production .NET Core workloads 😄 

I am creating an entity record using the CdsServiceClient. The record has a currency field. Upon executing the create request below using the `Money` type:

```csharp
_cdsService.Create(new Entity("abc_entity")
    {
        ["abc_amount"] = new Money(650.00m)
    });
```
I receive the the exception message: 

**HttpOperationException - POST abc_entities: Create To CDS via IOrganizationService |=> An error occurred while validating input parameters: Microsoft.OData.ODataException: Cannot convert a value to target type 'Edm.Decimal' because of conflict between input format string/number and parameter 'IEEE754Compatible' false/true.**

I am using **Microsoft.PowerPlatform.Cds.Client** version: 0.2.4-Alpha. The same request works when using **Microsoft.Xrm.Sdk** version 9.x.

I had a quick look at the source for CdsServiceClient and by best guess is the cast exception is being rasied at the below line, seeing as I am providing an object of type `Money`:
https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/7ef237ac91d9f47d698d9561c512231d28f7ac72/src/GeneralTools/CDSClient/Client/CdsServiceClient.cs#L4661

I understand that this library is using the OData Web API endpoint primarily to interface with CDS, so the JSON payload needs to mimic the OData requests we carry out normally. In fact, if I use a decimal in the request (below) directly, it works just fine.

```csharp
_cdsService.Create(new Entity("abc_entity")
    {
        ["abc_amount"] = 650.00m
    });
```

**Comment by MattB-msft** [comment]
Thanks for the find. will take a look at this and get a fix moving for it.

**Comment by MattB-msft** [comment]
As an updated we have a fix for this one and are in flight on checking it in to get it moved out here. 
thanks for your report!
