### ISSUE TITLE
Unable to find a stable package Microsoft.Powerplatform.Cds.Client with version (>= 0.0.0.1)

### ISSUE THREAD

**Issue by skfd** [microsoft/PowerPlatform-CdsServiceClient#3]
How do I install this `nuget` package?

```
nstall-Package : NU1103: Unable to find a stable package Microsoft.Powerplatform.Cds.Client with version (>= 0.0.0.1)
  - Found 3 version(s) in nuget.org [ Nearest version: 0.0.1.6-alpha ]
```

**Comment by aidanoleary** [comment]
@skfd Are you including the flag to say that you also want to include pre-release packages?
https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages

**Comment by skfd** [comment]
* Tried to do it from Rider UI -- it lists the 0.0.1.8-alpha version when I add _prereleases_ checkmark.
* Tried to do the same in VS
* Tried `dotnet add . package Microsoft.Powerplatform.Cds.Client.Dynamics --version 0.0.1.8-Alpha`

What worked for me is to do this from "Package Manager Console" in VS:
`Install-Package Microsoft.Powerplatform.Cds.Client.Dynamics -IncludePrerelease -Version 0.0.1.8-Alpha`

**Comment by jordimontana82** [comment]
If helps, I've tried with dotnet 3.1  and it works... but I didn't install the package, just added it manually to the .csproj and then dotnet restore.

**Comment by skfd** [comment]
Ok, looks like you need to install `Microsoft.Powerplatform.Cds.Client` first, then `Microsoft.Powerplatform.Cds.Client.Dynamics`. Installing only `Microsoft.Powerplatform.Cds.Client.Dynamics` -- fails.
