### ISSUE TITLE
Does this library use httpsclientfactory for resilient http requests?

### ISSUE THREAD

**Issue by UM001** [microsoft/PowerPlatform-CdsServiceClient#32]
I am wondering if this library meets this advice regarding httpclient. I did not see a way to pass own handler to make httpclient strong typed.

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

**Comment by MattB-msft** [comment]
@Um001 This client currently uses httpClient vs HttpClientFactory for those messages and types that utilize the webAPI,  not all do.   We are still evaluating if we can utilized either httpClientFactory or some variation there of that works for our needs. 

you can see that in the code here: https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/2dba0cf766985cbf72ccfb8381b23f918749cc09/src/GeneralTools/CDSClient/Client/CdsConnectionService.cs#L1380
We do not expose the httpclient services it uses outside of its runtime as the connection services are managed by the client based on the instructions its given,  this allows us to update and or change how we talk to the server without impacting code that is using this library. 

We do support retry's, throttling and such using the methods and processes that are exposed by the CDS Server..  We also allow end users a level of control over these settings on a pre client instance. 

I hope that helps clarify this.
