### ISSUE TITLE
Issue setting a Date field to a null value.

### ISSUE THREAD

**Issue by bguidinger** [microsoft/PowerPlatform-CdsServiceClient#34]
With the change to Web API, updates to set a Date/Time field to null are failing.  For example, this code throws an exception with an error response from the Web API.

```
var entity = new Entity("entity", guid)
entity["new_datetimefield"] = null;

service.Update(entity);
```

Error:

```
DateTime is less than minumum value supported by CrmDateTime. Actual value: 01/01/0001 00:00:00, Minimum value supported: 01/01/1753 00:00:00"
```

This was working on 0.2.1, but is failing on 0.2.5+

**Comment by MattB-msft** [comment]
Thanks .. Looking into this.

**Comment by MattB-msft** [comment]
confirmed bug.. we will get this fixed in the next drop.

**Comment by pksorensen** [comment]
"With the change to Web API" - what does that mean, did you swap such the client talks with odata endpoint instead of soap?

**Comment by MattB-msft** [comment]
Yes,  all create update and delete operations are now running via the web api. 

Though from the consumer view there is no change. 

Thanks
MattB
