### ISSUE TITLE
System.NullReferenceException in CdsServiceClient constructor 

### ISSUE THREAD

**Issue by gashupl** [microsoft/PowerPlatform-CdsServiceClient#35]
When I'm try to create new CdsServiceClient with single string argument (representing CDS connection string)  constructor - I'm getting: "System.NullReferenceException: 'Object reference not set to an instance of an object.'" error every time. 
   
var client = new CdsServiceClient(connectionString);

I'm not sure it is because the connection string is invalid (but even in case it is - I assume that this error should be handled and not throwing NullReferenceException) or because of the some other reason...

I'm using 0.2.14 Nuget package version. Tried it in windows console app (both .NET Framework and .NET Core based).

**Comment by dsmeltz** [comment]
The package doesn't currently support connection strings.
> We are supporting only Client Secret / Cert flows for .net core. On .net framework additionally we support OAuth User flows

**Comment by MattB-msft** [comment]
We do support connection strings for Client Secret and Cert flows in .net core. 
@gashupl  can you provide the structure of the connection your using?  

we would need to know what your trying to help.

**Comment by gashupl** [comment]
Ok. My mistake. I have an error inside my connection string. I have missing Url= part:

AuthType=Office365;**Url=**https://xxx.crm4.dynamics.com/;Username=admin@Cxxx.onmicrosoft.com;Password=xxx. 

Still I think that the error message should be more friendly, for example: "Invalid connection string format" or something :). 
Thank you for your time. 
The issue may be closed.
