### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by Ruud-cb** [microsoft/PowerPlatform-CdsServiceClient#36]
Hi,

Is there a practical limitation as why the library cannot support .NET Standard? Most of the services I have are all in .NET Standard and can thus be called from any other .NET Standard project. Using this package would require me to either change all 30+ projects to .NET Core, which is not desired, or 'workaround' the issue by having a web project pull the data and then use the .NET Standard project to store the data in the database. I would prefer to call the service from a business logic, which is a .NET Standard project. 

Any plans for .NET Standard?
Thanks!

**Comment by MattB-msft** [comment]
its a practical limitation. 
.net standard 2.x is missing some of the data contact processors that are in .net 4.8 which prevents us from running on it. 

We have been discussing this with the .net team.. but no ETA for support at this point, even so, any support would be in a future version of .net.

**Comment by Misiu** [comment]
@MattB-msft any updates on this?
I have a legacy project that I'd like to port step-by-step, so all my common classes should ideally target Standard 2.0.
This way I'll be able to use the same code in .NET Framework 4.6.2 (legacy project) and .NET 6.0

**Comment by Ruud-cb** [comment]
> @MattB-msft any updates on this? I have a legacy project that I'd like to port step-by-step, so all my common classes should ideally target Standard 2.0. This way I'll be able to use the same code in .NET Framework 4.6.2 (legacy project) and .NET 6.0

Depends on your purpose, but at the time I ended up writing my own Dynamics integration with just `HttpClient` using the `/api/data/v9.1/{entity}` endpoints. In the end it's just a OData API. Gives me some more flexibility then previous didn't think of I needed.

**Comment by MattB-msft** [comment]
@Misiu We provide both .net framework and .net core targets for this purpose.

**Comment by Misiu** [comment]
@MattB-msft I've noticed that :) THank you for the reply.
