### ISSUE TITLE
Question: OAuth connections string example for on-premise backend service

### ISSUE THREAD

**Issue by skfd** [microsoft/PowerPlatform-CdsServiceClient#4]
I found a [success story](https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/255985/crm2016-afds-authentication?pifragment-97030=1#responses) for this scenario, but it involves doing manual two-step retrieval of the token. I assume SDK will do it internally. But I don't think there is an example of connection string for OAuth for on-premise backend service.

Could you help us with that?

**Comment by MattB-msft** [comment]
You can do this with this client on full framework .net
and example of that connection string is here: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect#oauth-using-current-logged-in-user-with-fall-back-ux-to-prompt-for-authentication

if your running on .net core,  you must use one the S2S flows or roll your own token acquire flow using the constructor for the CdsServiceClient that accepts a function to retrieve tokens. 
if that is what your trying to do I can provide a short function example if you need,  we do not have the formal samples completed yet.

**Comment by MattB-msft** [comment]
Going to close it as, given that you didn't respond, I assume it worked for you

**Comment by senj** [comment]
> if your running on .net core, you must use one the S2S flows or roll your own token acquire flow using the constructor for the CdsServiceClient that accepts a function to retrieve tokens.
> if that is what your trying to do I can provide a short function example if you need, we do not have the formal samples completed yet.

Hi @MattB-msft , can you please provide the example for me?
