### ISSUE TITLE
CdsServiceClient - unspecific error messages are returned

### ISSUE THREAD

**Issue by stvonolf** [microsoft/PowerPlatform-CdsServiceClient#45]
Hi,
It seems after you switched from SOAP to WebAPI backend, the error messages returned by the CdsServiceClient are very generic. 

Examples:
- Create entity with missing mandatory attribute:
Microsoft.Rest.HttpOperationException: 'Operation returned an invalid status code 'BadRequest''
Expected: more specific exception indicating missing/invalid attributes of entity

- Create entity using impersonation - passing invalid CallerId (random Guid)
JsonReaderException: Bad JSON escape sequence: \x. Path '_error', line 1, position 170.
Expected: exception indicating that callerId is invalid

There might be more cases like that - please verify.

Regards,
Stefan

**Comment by MattB-msft** [comment]
Some of this is a byproduct of the webAPI error reporting levels today. 
the team is making progress on improving the error reporting there to be more useful. 

We will have a look at the particular errors your pointing at and see if there is a miss in interfering in the client.  

thanks for raising this issue. 

MattB

**Comment by MattB-msft** [comment]
Took a look at this and there are a few things here.. 

1) yes.. the errors between webAPI and OrgService are not consistent,  I am raising that to the API team currently.   


2) the actual error **is** being reported by the CDS client. 
The Exception of "Bad Request" is accurate... its a HttpOperationException, you can decode that to get to the messages. 
We do attach the decoded message as LastError in the CdsService Client.. 

For example:
trying to create an account entry passing an invalid property results in a LastCdsError of : 
************ HttpOperationException - POST contacts : User Defined |=> An error occurred while validating input parameters: Microsoft.OData.ODataException: Does not support untyped value in non-open type.

and an Exception of type HttpOperationException will be in the LastCdsExecption, and thrown if your using the basic IOrganziation Service Cmds. 


We could look at attaching additional errors to this to split it out for you, but what the Service is complaining about is there.
