### ISSUE TITLE
ShouldRetryWebAPI seems to always use default value instead of retry-after header

### ISSUE THREAD

**Issue by stvonolf** [microsoft/PowerPlatform-CdsServiceClient#47]
Hi,
There seems to be a bug in _ShouldRetryWebAPI_  - the default value is always used. 

See line 5738 - there should be an _else_ condition:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/69305614/91065089-5c534080-e630-11ea-9967-a364667bce9b.png)

Regards,
Stefan

**Comment by MattB-msft** [comment]
Added Fix for this in Linked PR
