### ISSUE TITLE
The HTTP request was forbidden with client authentication scheme 'Anonymous'

### ISSUE THREAD

**Issue by BetimBeja** [microsoft/PowerPlatform-CdsServiceClient#5]
Hello,
the CdsServiceClient throws an exception when trying to use the ClientSecret authentication and you have not registered the application in the dynamics instance yet. The stack trace is the following:

```
Microsoft.Powerplatform.Cds.Client.Utils.CdsConnectionException
  HResult=0x80131500
  Message=Failed to connect to Common Data Service
  Source=Microsoft.Powerplatform.Cds.Client
  StackTrace:
   at Microsoft.Powerplatform.Cds.Client.CdsServiceClient.CreateCdsServiceConnection(Object externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential credential, String userId, SecureString password, String domain, String Geo, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, OrganizationWebProxyClient externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned, Boolean useDefaultCreds)
   at Microsoft.Powerplatform.Cds.Client.CdsServiceClient..ctor(Uri instanceUrl, String clientId, String clientSecret, Boolean useUniqueInstance, String tokenCachePath)
   at CDS.Core_Test.Program.Main(String[] args) in C:\Demo\CDS.Core Test\CDS.Core Test\Program.cs:line 17

  This exception was originally thrown at this call stack:
    Microsoft.Powerplatform.Cds.Client.CdsConnectionService.InitCdsService()
    Microsoft.Powerplatform.Cds.Client.CdsConnectionService.GetCachedCDSService(out Microsoft.Powerplatform.Cds.Client.CdsConnectionService)
    Microsoft.Powerplatform.Cds.Client.CdsConnectionService.IntilizeService(out Microsoft.Powerplatform.Cds.Client.CdsConnectionService)
    Microsoft.Powerplatform.Cds.Client.CdsConnectionService.DoLogin(out Microsoft.Powerplatform.Cds.Client.CdsConnectionService)
    Microsoft.Powerplatform.Cds.Client.CdsServiceClient.CreateCdsServiceConnection(object, Microsoft.Powerplatform.Cds.Client.AuthenticationType, string, string, string, System.Net.NetworkCredential, string, System.Security.SecureString, string, string, string, bool, bool, Microsoft.Xrm.Sdk.Discovery.OrganizationDetail, Microsoft.IdentityModel.Clients.ActiveDirectory.UserIdentifier, string, System.Uri, Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior, string, Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient, string, System.Security.Cryptography.X509Certificates.StoreName, System.Security.Cryptography.X509Certificates.X509Certificate2, System.Uri, bool, bool)

Inner Exception 1:
MessageSecurityException: The HTTP request was forbidden with client authentication scheme 'Anonymous'.
```

You can use the following code to replicate the problem:
```csharp
using Microsoft.Extensions.Configuration;
using Microsoft.Powerplatform.Cds.Client;
using System;
using System.IO;

namespace CDS.Core_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            IConfiguration config = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory())
                                            .AddJsonFile("appsettings.json", true, true)
                                            .Build();
            var cdsClientConfig = config.GetSection("CdsClient");

            var cdsClient = new CdsServiceClient(new Uri(cdsClientConfig["Uri"]), cdsClientConfig["ClientId"], cdsClientConfig["ClientSecret"], true, cdsClientConfig["TokenCache"]);
            if (cdsClient.IsReady)
            {
                Console.WriteLine("Hello, connected to CDS using .NET Core");
            }
            else
            {
                // Never reaches this line of code because the constructor throws an exception
                Console.WriteLine("Failed to connect to CDS using .NET Core :(");
            }

            Console.ReadKey();
        }
    }
}
```

I replicated the same situation using CrmServiceConnection from Microsoft.Xrm.Tooling.Connector and it does not throw an exception, instead, it handles the exception and stores it in the `CrmServiceClient.LastCrmException` property. You can use the following code to replicate it using .Net Framewrork 

```csharp
using Microsoft.Xrm.Tooling.Connector;
using System;
using System.Configuration;

namespace CrmServiceClient_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var appSettings = ConfigurationManager.AppSettings;
            var crmClient = new CrmServiceClient(new Uri(appSettings["Uri"]), appSettings["ClientId"], appSettings["ClientSecret"], true, appSettings["TokenCache"]);
            if (crmClient.IsReady)
            {
                Console.WriteLine("Hello, connected to Dynamics using .NET Framework");
            }
            else
            {
                Console.WriteLine("Failed to connect to Dynamics using .NET Framework :(");
                //this works without an exception
            }


            Console.ReadKey();
        }
    }
}
```
Actually `CrmServiceClient.LastCrmException` does not have an InnerException and contains no Trace information and the most meaningfull information I got from this (by configuring Visual Studio to break on thrown exceptions) is the following:
```
Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.HttpRequestWrapperException
  HResult=0x80131500
  Message=
  Source=Microsoft.IdentityModel.Clients.ActiveDirectory
  StackTrace:
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsync>d__31.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

Inner Exception 1:
HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

Inner Exception 2:
AdalException: : Unknown error
```  
```
System.ServiceModel.Security.MessageSecurityException
  HResult=0x80131501
  Message=The HTTP request was forbidden with client authentication scheme 'Anonymous'.
  Source=System.ServiceModel
  StackTrace:
   at System.ServiceModel.Channels.HttpChannelUtilities.ValidateAuthentication(HttpWebRequest request, HttpWebResponse response, WebException responseException, HttpChannelFactory`1 factory)

  This exception was originally thrown at this call stack:
    System.Net.HttpWebRequest.GetResponse()
    System.ServiceModel.Channels.HttpChannelFactory<TChannel>.HttpRequestChannel.HttpChannelRequest.WaitForReply(System.TimeSpan)

Inner Exception 1:
WebException: The remote server returned an error: (403) Forbidden.
```

**Comment by MattB-msft** [comment]
Thanks for the report,   This is actually the behavior of the API endpoint in CDS coming though.. as the identity your trying to access with does not exist, it does not know what the do with it and throws a 403,   We are looking at ways to make that message better from the API itself.  More similar to the "user does not exist in this instance" error we used to throw when trying to access an instance where your user identity was blocked by security or policy.

**Comment by BetimBeja** [comment]
One thing I did not specify clearly is that the `CdsServiceClient` constructor throws exceptions and instead the `CrmServiceClient` constructor catches the exception and puts it in the `CrmServiceClient.LastCrmError` property.

**Comment by MattB-msft** [comment]
Yes, this is intentional..   CrmServiceClient follows a C++ pattern for exception management from when it was originally designed many years ago.   We wanted to move over to the more common "throw breaking exception on connect fail" but could not without breaking a lot of existing clients.   Adding a Option to the constructor or a static setting didn't make sense either so we lived with it. 

also: re the exception stack trimming things,  we did a fix for that recently that will now include the full stack though all levels,  if you patch to current nuget's you will get that behavior. 


With CdsServiceClient we moved to using Exceptions on connect.  Its noted in the nuget release notes.   We have not yet decided if we are going to do away with the LastException pattern completely yet.. but for now it will always throw exceptions on connect, which is the more accepted pattern today.

Feedback is welcome on that.

**Comment by twiga2013** [comment]
I am so excited that finally there will be client library that we can use from .NET Core applications when interacting with Dynamics CRM. Thank You!!

Is there a resolution to this issue? I am getting the same error message when using Client ID and Client Secret connecting to Dynamic 365 CRM Online. Thanks again

**Comment by BetimBeja** [comment]
Hello @twiga2013,
you have to register your application user in dynamics, the issue has been opened because the error message is misleading.

I have written a LinkedIn [Article](https://www.linkedin.com/pulse/microsoftpowerplatformcdsclient-betim-beja/) on how to build an MVP for this.

Best regards,
Betim.

**Comment by twiga2013** [comment]
Hi Betim,

I have created the App Registration under the same Azure Active Directory that CRM Dynamics is using but when I got to add Application user all the fields are locked and I am logged in Dynamics as System Administrator.

**Comment by MattB-msft** [comment]
@twiga2013 , Change the user view from "user" to "Application User"

**Comment by twiga2013** [comment]
I did switch to Application User form everything is locked. I did try it out from a complete different tenant and Application User forms fields are not locked. 

I will need to contact Microsoft support to find out why the application user form fields are all locked.

**Comment by MattB-msft** [comment]
I am going to close this for now,  the API team has a repro of this working now and is working though providing a better error experience. 

thanks all for your feedback here.
