### ISSUE TITLE
Key Attribute Support missing for Entity Reference fields when using CdsServiceClient

### ISSUE THREAD

**Issue by smfpride** [microsoft/PowerPlatform-CdsServiceClient#50]
I noticed that CdsServiceClient does not support setting a lookup field using Key Attributes, it seems that the support for that is missing in Utilities.ToExpandoObject. The functionality still works if you are using the OrganizationWebProxyClient.

An example is: 
```
KeyAttributeCollection lookupKeys = new KeyAttributeCollection();
lookupKeys.Add(new KeyValuePair<string, object>("tickersymbol","AMZN"));
someContact["parentcustomerid"] = new EntityReference("account", lookupKeys};
```

I found that key support does exist for referencing the primary entity (someContact in my sample above), https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/bd5dee5c8ecef545b2cede3fcaedc0fff0fa7abf/src/GeneralTools/CDSClient/Client/CdsServiceClient.cs#L4983

I put together a quick sample of how it could be implemented in ToExapandoObject (although really it should probably it's own method in Utilities just for formatting Entity Reference identifier).

https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/bd5dee5c8ecef545b2cede3fcaedc0fff0fa7abf/src/GeneralTools/CDSClient/Client/Utils/Utils.cs#L354

```
string entRefIdentifier;

if (entityReference.KeyAttributes?.Any() == true)
{

	string keycollection = string.Empty;
	foreach (var itm in entityReference.KeyAttributes)
	{
		if (itm.Value is EntityReference er)
		{
			keycollection += $"_{itm.Key}_value='{er.Id.ToString("P")}',";

			//IEnumerable<string> keys = cReq.KeyAttributes.Select(s => $"_{s.Key}_value='{((EntityReference)s.Value).Id.ToString().Replace("'", "''")}'");
			//keycollection += $"{EntityData.EntitySetName}({string.Join("&", keys)})";

			//if (cReq.Id != Guid.Empty)
			//{
			//    var s2 = EntityData.EntitySetName + cReq.Id.ToString("P");
			//}


			//// Add support for ER for KEY. 
			//keycollection += $"{itm.Key}@odata.bind='{$"/{metadataUtlity.GetEntityMetadata(Xrm.Sdk.Metadata.EntityFilters.Entity, er.LogicalName).EntitySetName}({er.Id})"}',";
		}
		else 
		{
			keycollection += $"{itm.Key}='{itm.Value}',";
		}
	}
	entRefIdentifier = keycollection.Remove(keycollection.Length - 1); // remove trailing , 
}
else
{
	entRefIdentifier = $"{entityReference.Id}";
}

value = $"/{mUtil.GetEntityMetadata(Xrm.Sdk.Metadata.EntityFilters.Entity, entityReference.LogicalName).EntitySetName}({entRefIdentifier})";
```

**Comment by MattB-msft** [comment]
thanks for the comments.. there are a few areas like this where the translation is a bit rough.  We will get this fixed.

**Comment by mathiasbl** [comment]
I think I'm hitting the same problem. Getting BadRequests when using key attributes to resolve lookups.

``` csharp
var entity = new Microsoft.Xrm.Sdk.Entity("rkv_interdonationinterval", "rkv_ctscode", $"1_1");
entity["rkv_donationinterval"] = 80;
entity["rkv_previousdonationtypeid"] = new EntityReference("rkv_donationtype", "rkv_ctscode", "1");
entity["rkv_nextdonationtypeid"] = new EntityReference("rkv_donationtype", "rkv_ctscode", "1");

_organizationService.Execute(new UpsertRequest { Target = entity });
```

The above works using the old CrmServiceClient.
