### ISSUE TITLE
Support for Azure Functions v1?

### ISSUE THREAD

**Issue by filcole** [microsoft/PowerPlatform-CdsServiceClient#52]
Does CdsServiceClient support Azure Functions v1?  

The Azure functions v1 runtime (Microsoft.NET.Sdk.Functions v1.0.37) provides *exactly* Newtonsoft.Json = 9.0.1.  Yet CdsServiceClient requires Newtonsoft.Json >= 10.0.0.3.  When using Visual Studio 2019 to install nuget package Microsoft.CdsServiceClient in a Azure Functions v1 project the following error is given.

```
Restoring packages for C:\dev\AxisK2\FunctionApp10\FunctionApp10.csproj...
NU1107: Version conflict detected for Newtonsoft.Json. Install/reference Newtonsoft.Json 10.0.3 directly to project FunctionApp10 to resolve this issue. 
 FunctionApp10 -> Microsoft.PowerPlatform.Cds.Client 0.2.17-Alpha -> Newtonsoft.Json (>= 10.0.3) 
 FunctionApp10 -> Microsoft.NET.Sdk.Functions 1.0.37 -> Newtonsoft.Json (= 9.0.1).
```

If Newtonsoft.Json is upgraded to 10.0.3 (or later) the Azure Function still runs, but anything that requires serialisation will have errors at runtime, examples being:

1. SwaggerUI/Swagger generation via [Aliencube.AzureFunctions.Extensions.OpenApi](https://github.com/aliencube/AzureFunctions.Extensions) - see [issue #121](https://github.com/aliencube/AzureFunctions.Extensions/issues/121) 
2. [Durable functions](https://github.com/Azure/azure-functions-durable-extension)

There are no problems on Azure Functions v3, which I believe is due to its runtime supporting Newtonsoft.Json >= 11.0.2.

This issue with Azure Functions v1 is present with both this CdsServiceClient and XrmTooling from 9.1.0.26 onwards.  XrmTooling 9.1.0.21 and prior required Newtonsoft 6.0.8 and so this issue is not present.

**Comment by MattB-msft** [comment]
Yes, we are aware of this and discussed with the functions team.  
Our dependency is tied to the version of Newtonsoft that the CDS Platform itself uses as a min,  unfortunately that requires us to keep the min supported at v10.   

We were told that the functions team is planning on Phasing out the V1 support, and thus we have not looked into creating a fork to allow for it.

**Comment by filcole** [comment]
Hi @MattB-msft,

Thanks for the reply. Unfortunately, that leaves us between a rock and a hard place as I see it.  Either:

#### A) Use V1 Azure Functions and an old version of XrmTooling (9.1.0.21)

- We have reasonably straight forward migration path from XrmTooling to CdsServiceClient when it does go GA.
- Until the CdsServiceClient is GA this puts at risk of having no answer/resolution if 
      - later version of XrmTooling is required (due to bugs/platform changes) or,
      - if V1 Azure Functions is killed

#### B) Eschew XrmTooling and use Azure Functions v3 calling the WebApi directly

- We lose all the benefits of XrmTooling such as authentication, Throttling/Retry, using EarlyBound classes, Linq, consistent coding style between plugins/Azure. 
- It's unlikely that we'd be able to justify moving back to CdsServiceClient at a later date due to the cost of the change.

What would you advise clients/partners to do?

**Comment by MattB-msft** [comment]
any reason you cannot use the pre-compiled package process?
that should not require you to depend on any specific version of functions dependencies.

**Comment by justinyoo** [comment]
@filcole I wrote a blog post as a workaround for your enterprise scenario, which is still valid. Please have a look: https://devkimchi.com/2020/11/11/openapi-extension-to-support-azure-functions-v1/
