### ISSUE TITLE
An item with the same key has already been added. Key: msdyn_iotalert.msdyn_customerasset

### ISSUE THREAD

**Issue by bipinshan** [microsoft/PowerPlatform-CdsServiceClient#55]
We have Azure function where we are creating IoT Alert Entity record in Dynamics CRM.

**Code Snippet to Create Record**

Entity newAlert = new Entity("msdyn_iotalert");
newAlert["msdyn_alertdata"] = JsonConvert.SerializeObject(Data);
newAlert["msdyn_alerttime"] = DateTimeOffset.Parse(ActiveTime, CultureInfo.CurrentCulture);
newAlert[msdyn_alerttype] = 192350000;
newAlert[msdyn_description] = Name;
newAlert["statecode"] = 0;
newAlert["statuscode"] = 1;
newAlert["msdyn_CustomerAsset"] = new EntityReference("msdyn_customerasset", assetId);
Guid alertId = this.cdsServiceClient.Create(newAlert);

Earlier I have raised bug regarding Lookup field Entityreference issue which was fixed so updated our code to use Schema name in upper case letter. https://github.com/microsoft/PowerPlatform-CdsServiceClient/issues/44

**Error Log** 
[
{
"parsedStack":[
{
"assembly":"System.Private.CoreLib,Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
"level":0,
"line":0
},
{
"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
"method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__21.MoveNext",
"level":1,
"line":338,
"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral,PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
"level":2,
"line":0
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
"level":3,
"line":0
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral,PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
"level":4,
"line":0
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult",
"level":5,
"line":0
},
{
"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
"method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsyncCore>d__18.MoveNext",
"level":6,
"line":123,
"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"
}
],
"severityLevel":"Error",
"outerId":"0",
"message":"Exception while executing function: CreateAlertFromIconicsFault",
"type":"Microsoft.Azure.WebJobs.Host.FunctionInvocationException",
"id":"12012676"
},
{
"parsedStack":[{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException",
"level":0,
"line":0
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Collections.Generic.Dictionary`2.TryInsert",
"level":1,
"line":0
},
**{
"assembly":"Microsoft.PowerPlatform.Cds.Client, Version=0.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
"method":"Microsoft.PowerPlatform.Cds.Client.MetadataUtility.GetAttributeMetadata",
"level":2,
"line":0
},
{
"assembly":"Microsoft.PowerPlatform.Cds.Client, Version=0.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
"method":"Microsoft.PowerPlatform.Cds.Client.Utilities.ToExpandoObject",
"level":3,
"line":0
},
{
"assembly":"Microsoft.PowerPlatform.Cds.Client, Version=0.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
"method":"Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_WebAPIProcess_Execute",
"level":4,
"line":0
},
{
"assembly":"Microsoft.PowerPlatform.Cds.Client, Version=0.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
"method":"Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.ExecuteCdsOrganizationRequestImpl",
"level":5,
"line":0
},
{
"assembly":"Microsoft.PowerPlatform.Cds.Client, Version=0.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
"method":"Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.Create",
"level":6,
"line":0
},**
{
"assembly":"dynamics-connector,Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
"method":"DynamicsConnector.Dynamics.Services.DynamicsEntityService.CreateAlert",
"level":7,
"line":58,
"fileName":"D:\\ConnectorProject\\Workspace\\Repo\\fieldservice_240\\fieldservice\\src\\azure\\dynamics-connector\\dynamics-connector\\Dynamics\\Services\\DynamicsEntityService.cs"
},
{
"assembly":"dynamics-connector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
"method":"DynamicsConnector.Functions.CreateAlertFromIconicsFault+<Run>d__10.MoveNext",
"level":8,
"line":100,
"fileName":"D:\\ConnectorProject\\Workspace\\Repo\\fieldservice_240\\fieldservice\\src\\azure\\dynamics-connector\\dynamics-connector\\Functions\\CreateAlertFromIconicsFault.cs"
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
"level":9,
"line":0
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
"level":10,
"line":0
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
"level":11,
"line":0
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter.GetResult",
"level":12,
"line":0
},
{
"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
"method":"Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2+<InvokeAsync>d__2.MoveNext",
"level":13,
"line":20,
"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\VoidTaskMethodInvoker.cs"
},
{
"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":14,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":15,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":16,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","level":17,"line":0},
{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
"method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2+<InvokeAsync>d__10.MoveNext","level":18,
"line":52,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs"},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":19,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":20,"line":0},
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":21,
"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","level":22,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeAsync>d__29.MoveNext","level":23,"line":589,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":24,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":25,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":26,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.GetResult","level":27,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__28.MoveNext","level":28,"line":537,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":29,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":30,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":31,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.GetResult","level":32,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__27.MoveNext","level":33,"line":481,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":34,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":35,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":36,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.GetResult","level":37,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=3.0.19.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__21.MoveNext","level":38,"line":290,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"}],"severityLevel":"Error","outerId":"12012676","message":"An item with the same key has already been added. Key: msdyn_iotalert.msdyn_customerasset","type":"System.ArgumentException","id":"22757684"}]

**Comment by MattB-msft** [comment]
@bipinshan  sorry about the slow response here..  
The current release resolved the casing issue on properties by determining what it needed to from the related metadata path, 

In the case of the error message your getting now, CDS is saying that the msdyn_iotalert your creating already exists or is hitting a constraint created by an alt key. 

are you still hitting it?

**Comment by bipinshan** [comment]
@MattB-msft We have not added any Alternate key in IoT Alert entity. As a matter of fact we did not do any customization to IoT Alert entity. 

Yes, It is an intermittent issue and as part of the retry policy of Service Bus Topic this is getting resolved. But we want it to work at first instance.

Thanks for your help!

**Comment by JimDaly** [comment]
Can you reproduce the issue calling the Web API directly using PostMan?
Can you capture a Fiddler request/response using the code, perhaps from a console application rather than from Azure Function?

**Comment by Guilhermeslucas** [comment]
I was working on a project that this issue appeared as well! We were able to create a console application using .NET that reproduces the bug and its attached. Hope that helps!

[dynamics-feedback.zip](https://github.com/microsoft/PowerPlatform-CdsServiceClient/files/5517431/dynamics-feedback.zip)

**Comment by MattB-msft** [comment]
Thanks @Guilhermeslucas 
this repro helped us fined it.   it is not a connectivity issue, turns out to be a cross threading issue in the client itself. 

we are fixing this now.

**Comment by Guilhermeslucas** [comment]
Thank you so much @MattB-msft ! That explains so much, we were getting no bad requests with the fiddler proxy, what was pretty weird!
