### ISSUE TITLE
CDS OData Web APIs UpsertMultiple can not update records when entityCollection includes both update record and create record.

### ISSUE THREAD

**Issue by jitliu** [microsoft/PowerPlatform-CdsServiceClient#56]
The issue was logged as bug in Azure devops, and it was fixed. We hope we can get the uptake here. Details was sent via Email.

**Comment by MattB-msft** [comment]
This is an undocumented API and is not yet fully supported by the server platform. 
When the server fully supports it, the current CdsServiceClient will be able to access it.
