### ISSUE TITLE
SessionTrackingId is not not added to requests to OrganizationService

### ISSUE THREAD

**Issue by stvonolf** [microsoft/PowerPlatform-CdsServiceClient#57]
Hi,

We are trying to set the _CdsServiceClient.SessionTrackingId_ property to be able to correlate Asp.net core sessions to CDS calls.

When the _CdsServiceClient_ calls a WebAPI endpoint internally, the _SessionTrackingId_ is correctly added as the header _x-ms-client-session-id_. 

However, when the _CdsServiceClient_ calls the _OrganizationService_ internally, it seems that the _SessionTrackingId_  is not added to the request (analyzed using Fiddler).

Regards,
Stefan

**Comment by MattB-msft** [comment]
We have confirmed that this is working as intended. 

For example:  A request that routes via OrgSvc:

Header includes: 
POST https://<BLOCKED>/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.45.2071 HTTP/1.1
Authorization: Bearer <BLOCKED>
x-ms-client-request-id: 04e2fc80-d29b-46d3-851e-7f04a72f9eaa
**x-ms-client-session-id: 1ae2d44b-9306-475c-9f1a-fd11e40eeb3d**
SOAPAction: "http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/Execute"
Host: <BLOCKED>
Cookie: <BLOCKED>
Content-Length: 1511
Expect: 100-continue
Accept-Encoding: gzip, deflate

and body includes:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
 ....
    <x-ms-client-request-id xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">04e2fc80-d29b-46d3-851e-7f04a72f9eaa</x-ms-client-request-id>
    **<x-ms-client-session-id xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">1ae2d44b-9306-475c-9f1a-fd11e40eeb3d</x-ms-client-session-id>**
  </s:Header>
  <s:Body>
    <Execute xmlns="http://schemas.microsoft.com/xrm/2011/Contracts/Services">
      <request i:type="b:RetrieveCurrentOrganizationRequest" xmlns:a="http://schemas.microsoft.com/xrm/2011/Contracts" xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns:b="http://schemas.microsoft.com/crm/2011/Contracts">
        <a:Parameters xmlns:c="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
          <a:KeyValuePairOfstringanyType>
            <c:key>AccessType</c:key>
            <c:value i:type="d:EndpointAccessType" xmlns:d="http://schemas.microsoft.com/xrm/2014/Contracts">Default</c:value>
          </a:KeyValuePairOfstringanyType>
        </a:Parameters>
        <a:RequestId>04e2fc80-d29b-46d3-851e-7f04a72f9eaa</a:RequestId>
        <a:RequestName>RetrieveCurrentOrganization</a:RequestName>
      </request>
    </Execute>
  </s:Body>
</s:Envelope>

Could you share what message type your using ?

**Comment by stvonolf** [comment]
Hi Matt,
Sorry for not getting back to you earlier. I have dug deeper into the code and the issue seems to be related to cloning (for multi-threaded applications).

You can use this code to reproduce the issue:
`var cdsClient = new CdsServiceClient(connectionString);
 var clone = cdsClient.Clone();
 clone.SessionTrackingId = Guid.NewGuid();
 var query = new QueryExpression("contact");
 clone.RetrieveMultiple(query); // session tracking id is not sent`

Regards,
Stefan
