### ISSUE TITLE
Unable to commit when uploading the file to the entity file attribute

### ISSUE THREAD

**Issue by ziyuanl** [microsoft/PowerPlatform-CdsServiceClient#58]
Hi,

I'm Ziyuan from Dynamics SCM team. We keep receiving exceptions when committing the file upload to the entity file attribute.

Here's the exception message:
"contextUserId=00000000-0000-0000-0000-000000000000 does not map to a high-privileged user. Parameter'user'=xxxxxxxxxxx"

I searched the CDS repo and found the place from where the exception is thrown. [CrmSecLib](https://dev.azure.com/dynamicscrm/OneCRM/_git/CDS?_a=contents&version=GBv9.0_master&path=%2Fsrc%2FManagedPlatform%2FServer%2FCrmSecLib.cs)

It's from method CrmSecLib.VerifyUser. From the comments, it looks like a context issue when doing some validations on ExecutionContext and UserIdentityContext.

![image](https://user-images.githubusercontent.com/35202306/94359120-ba63bf80-00d7-11eb-819a-a9efc3457160.png)

We are using [file uploading samples](https://dev.azure.com/dynamicscrm/OneCRM/_search?action=contents&text=CommitFileBlocksUploadRequest&type=code&lp=code-Project&filters=ProjectFilters%7BOneCRM%7D&pageSize=25&result=DefaultCollection%2FOneCRM%2FCDS.FileStore.ResourceProvider%2FGBmaster%2F%2Fsrc%2FFileStorageDynamicsApiTest%2FCrmSdkSamples.cs), and our code is much like the method CommitFile in the sample.

We are sending CommitAnnotationBlocksUploadRequest via CDS client.
```
requestName = "CommitFileBlocksUpload";

commitRequest = new CommitFileBlocksUploadRequest
{
    BlockList = chunkList.ToArray(),
    FileContinuationToken = continuationToken,
    FileName = fileName,
    MimeType = contentType ?? "application/octet-stream",
};

var response = this.CdsServiceClient.Execute(commitRequest);
```

And our client is initialized using the following constructor:
`public CdsServiceClient(Uri instanceUrl, Func<string, Task<string>> tokenProviderFunction, bool useUniqueInstance = true);`

It looks like the user id is missing in CDS client or upload commit request. I'm looking forward to your kind suggestions.

**Comment by MattB-msft** [comment]
the UserID is present, as its required to be there for that interface to connect at all. 
as your using a relatively new feature, I suspect that there is a issue with the server side implementation itself.  Please route this via the internal channel we are using to discuss this.
