### ISSUE TITLE
CdsServiceClient Authorization Timing out after App Is Idle for long time

### ISSUE THREAD

**Issue by atear10** [microsoft/PowerPlatform-CdsServiceClient#60]
I am using CdsServiceClient in Azure Function and if we send a request which basically needs to connect to Dynamics 365 using CdsServiceClient then it is throwing exception with Authentication is Anonymous but with subsequent retry it works. Below is code for initializing CdsClient

        public CdsServiceClient Create(string connectionString)
        {
            _logger.TraceVerbose("Creating CrmServiceClient");
            CdsServiceClient client = new CdsServiceClient(connectionString);

            if (!client.IsReady)
            {
                _logger.TraceError("CrmServiceClient is not ready! Please check your connection string in your \"App.config\"");
            }

            _logger.TraceVerbose("Connected To CRM");
            return client;
        }

<img width="904" alt="upload" src="https://user-images.githubusercontent.com/17720180/95418345-ecd1b000-0954-11eb-801d-b66d6d317cf3.PNG">

**Comment by MattB-msft** [comment]
Could you give us a sense for "how long" ? 
this sort of situation usually appears when the token lifespan of the access token differs from the what Azure AAD is requiring. 

thanks

**Comment by atear10** [comment]
I don't have the exact time with me but yeah usually I see this error after I trigger the function approx. 1 hour of my previous run or somewhere near.  Is there a way to refresh the Token within the lifespan of AAD token automatically?

**Comment by MattB-msft** [comment]
We have exercised this a few different ways and are not seeing it repro.. the system is auto refreshing the token for client secret if the token expires within 15 seconds. 

There is a question on if what is happening is the token's reported expiration is different then what AAD is actually enforcing.  Do you happen to know if there is a conditional access policy that has been applied to your tenant? 

Comment on this... 
We are going to defer looking into this one any further as we are close to releasing the updated version of the auth stack using MSAL which materially changes how this is done.   MSAL internally handles determining token refresh more efficiently then ADAL.net did and we have shifted over to using the onboard token refresh behaviors in the upcoming release. 

Im going to park this for the moment and come back to it once we have shipped the updated MSAL based client.
