### ISSUE TITLE
BUG : EntityReference with keys not working for rest api

### ISSUE THREAD

**Issue by pksorensen** [microsoft/PowerPlatform-CdsServiceClient#61]
using Latest 0.2.24-Alpha.

I cant remember how ToEntityReference works normally, but i had to do a extension method to get a reference with keyValueCollection myself:
![image](https://user-images.githubusercontent.com/2718591/95700086-72e84200-0c46-11eb-889a-ae005892185b.png)

When using a update request where a keycollection contains a entity reference,
![image](https://user-images.githubusercontent.com/2718591/95700287-f6099800-0c46-11eb-9875-00aa87e8e4b8.png)

the URL generated do not get generated property and it uses the empty id 00000-000... 

![image](https://user-images.githubusercontent.com/2718591/95699988-30266a00-0c46-11eb-903c-d51a80ba6050.png)

**Comment by BetimBeja** [comment]
What is so different from this and #62 and #63?

Also `Entity.ToEntityReference()` is related to the SDK and not to this package as far as I know.

**Comment by pksorensen** [comment]
This was just the origianal starting point - i think the deeper issue is due to the way REST api calls are made. However i dont know if EntityReference() also skips keyattributes on normal sdk.

This is about ToEntityReference, and if this is how it works on dynamics plugins i guess its not a issue, just found it odd.

#62 #63 is about the way this SDK generate REST API calls.

**Comment by MattB-msft** [comment]
@pksorensen , Entity Ref using alt key's does work,  though its a recent fix.. 
Can you confirm your on the current release?
