### ISSUE TITLE
BUG: EntityReference UpdateReguest bad URL translation

### ISSUE THREAD

**Issue by pksorensen** [microsoft/PowerPlatform-CdsServiceClient#63]
Doing an update request against an entity that uses an lookup alternate key results in a bad URL:

Case: Contact Entity has a lookup field to related Entity SocialSecurityNo on field ka_cpr.

The patch reguest generated when adding a alternate key to the EntityReference: 
https://demolap.api.crm4.dynamics.com/api/data/v9.1/contacts(_ka_cpr_value='(00000000-0000-0000-0000-000000000000)')

It uses the empty Id of the entity reference and not the keycollection.

However i have not figured out how the URL should be manual either yet.
Somthing like?
https://demolap.api.crm4.dynamics.com/api/data/v9.1/contacts(_ka_cpr_value='socialsecuritynos(dca_socialsecurityno='xxxxxxxxxx')')

**Comment by MattB-msft** [comment]
In each of theses, you can revert to old behavior by using executorganizationrequest and passing useWebAPI as false, 

That will fall back to the older protocol while we resolve theses issues. 

MattB

**Comment by pksorensen** [comment]
Thanks @MattB-msft - where do i set useWebAPI = cant seem to find it?

**Comment by MattB-msft** [comment]
It's a parameter on that method call,  it has to be done per call.

**Comment by JimDaly** [comment]
@pksorensen 
Can you include the snippet of the CdsServiceClient code you are using?
I'm not clear on your intent.

**Comment by mathiasbl** [comment]
The method is called ExecuteCdsOrganizationRequest.

**Comment by pksorensen** [comment]
Its because many of use works wiht IOrganizationService, and did not notice theses. If instead the class is used, all these methods are there.

Also, just discovered that ExecuteCdsOrganizationRequest do not throw on error, it just returns null and you have to check yourself for the last error. Just imported 1.500.000 rows thinking everything vent fine :)

**Comment by MattB-msft** [comment]
Sorry about the wrong message name :) working off my phone and memory. 

Regarding the null return process,  yes that is the older pattern that the crmserviceclient uses. We wrap it with an exception throw patten when you use the iorganizationservice interfaces.  

It's something we changed in the cdsserviceclient for iorganizationservice interfaces.

The older pattern is the lastError pattern,  thus on a null return, check last error for the actual error that were generated.

**Comment by pksorensen** [comment]
Everything makes sense now, also found some othre nice stuff from using CdsServiceClient directly.

On that note with LastError Pattern, i just vent over the code - dont the implemented way cause a potential thread issue?
I noticed how the locking happens inside the ExecuteCdsOrganizationRequest call and the lock is released before it reaches the 
`If(lastError) throw LastError` ? so if doing a lot of parallel requests, then the last error can be reset before it reaches the throw step.

To make sure that do not happen for me, i moved the lock further out.

```
  private object lockobject = new object();
        public T Execute<T>( OrganizationRequest reg, bool userApi = false)

            where T : OrganizationResponse
        {
            lock (lockobject)
            {
                var os = service as CdsServiceClient;
                var a = os.ExecuteCdsOrganizationRequest(reg, useWebAPI: userApi) as T1;
                if (a == null)
                    throw os.LastCdsException;
                return a;
            }
             
        }
```

**Comment by MattB-msft** [comment]
The tracer creates a stack of errors, and traces are specific to the particular connection.  the Lock behavior is there to prevent one calling thread from interrupting a connection via WCF that was initiated by a different calling thread,  LastError will be active at the moment of the call. 

Its also why we guide folks to use the .clone process as that bypasses this whole issue and prevents one connection waiting on another connection problems. 

The issue is the same with the HTTP Client , however it provides some built into call back mechanic's to help deal with it so the implementation there is a bit different.

**Comment by MattB-msft** [comment]
@pksorensen  we looked more in depth at this.
can you provide a snip of how your making this call?  We have code currently in place that should auto route this back to the organization web service for Upsert requests
