### ISSUE TITLE
[Question] Any ETA please?

### ISSUE THREAD

**Issue by anskanth** [microsoft/PowerPlatform-CdsServiceClient#65]
Hi

Now that it's been a few months, are you seeing any ETA for GA? Any plans? We are desperate to use this in our Azure functions to connect to CDS,

Thank you
-Srikanth

**Comment by MattB-msft** [comment]
Per the ReadMe :)  the current plan is to take this to beta as we ship the update that replaces ADAL.net with MSAL support.  that code is mostly done and being tested now. 

Post Beta, we will start the process of moving to GA for 1.0.
