### ISSUE TITLE
CDS calls are made with two different user agents

### ISSUE THREAD

**Issue by stvonolf** [microsoft/PowerPlatform-CdsServiceClient#66]
Seems like there may be a mix of logging as most services have 2 versions of User Agent, with and without the CdsSvcClient info. We would need to consolidate useragent value so CDS can monitor traffic (and for our own usage as well). 

Examples:
Some calls are made with useragent "ServiceName", some with useragent "ServiceName (CdsSvcClient:0.0.2.25)".

Could this be due to the fact that CdsServiceClient splits the calls between SOAP and REST endpoints?

**Comment by MattB-msft** [comment]
This is indeed a bug,  the proper format should be "ServiceName (CdsSvcClient:0.0.2.25)"
we will get this sorted.

**Comment by MattB-msft** [comment]
Fix is queue for this currently.
