### ISSUE TITLE
BUG: ExecuteCdsWebRequest doesn't re-authenticate after 1 hour (eg. token expiration)

### ISSUE THREAD

**Issue by hajekj** [microsoft/PowerPlatform-CdsServiceClient#67]
Hi there,

we noticed, that when we have CdsServiceClient in DI as Singleton (eg. lifetime of the application), after 1 hour the calls to CDS start failing with 401 errors. We are using the `client_credentials` authentication with client ID and client secret (not certificate).

I have been trying to find the exact issue in the code, but didn't really get far enough. One workaround for us is to change the lifetime to scoped, but the will basically lower the efficiency of the token cache and thus request a token with each incoming request.

We are running on .NET Core 3.1 with `0.2.24-Alpha` version of this library. Would be happy to dig deeper and submit a PR even, but the README doesn't give much hints on doing it properly.

---
Probably related to #60

**Comment by MattB-msft** [comment]
Hi @hajekj, 
this is a dup of another report..  We are deferring this right now as we are about to ship an revision of the whole authentication system for the connector, moving over to MSAL from ADAL.net. 

What I would ask is that once that drop ships, you uptake that and see if you still have the issue. 

We believe it has something to do with the ADAL.net .net core implementation.
