### ISSUE TITLE
Asynchronous API

### ISSUE THREAD

**Issue by pierceboggan** [microsoft/PowerPlatform-CdsServiceClient#7]
As a .NET developer, I expect to be able to use the [`async`/`await`](https://docs.microsoft.com/en-us/dotnet/csharp/async) keywords to perform data operations asynchronously.

This is especially important when working with data-intensive applications and populating UI from a data source (such as Common Data Service) so my UI thread does not lock while fetching data.

**Comment by BetimBeja** [comment]
It would be really nice to have an implementation of `IOrganizationService{Async}` since the use case for the CdsServiceClient is for external clients, and not for the implementation of `Plugin` or `Code Activity` logic.

For the time being an `IOrganizationService{Async}` interface is not available from Microsoft that I am aware of.

**Comment by jordimontana82** [comment]
Not aware of any, and not because we didn't request that previously! : )  It would be nice to get this added, if possibly the external .Execute method is exposed as async, then all the other requests could "inherit" from that implementation really...

**Comment by mathiasbl** [comment]
If you really need TAP for your application, you can use HttpClient to interact with the CDS Web API.
The Web API implements the OData v4 which is a standard. 

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/overview

**Comment by MattB-msft** [comment]
Async support is being discussed at several levels for this lib. 
Note that this lib does use WebAPI for some operations currently, and will use it more so over time as issues are resolved to support cross compatibility.
