### ISSUE TITLE
Getting exception "An error occurred while validating input parameters: Microsoft.OData.ODataException: Does not support untyped value in non-open type." while setting party list field.

### ISSUE THREAD

**Issue by vanita1012** [microsoft/PowerPlatform-CdsServiceClient#70]
Hi Team,
I am creating a phone call using C# code and setting the party list fields from and to using below code:- 
            Entity phonecall = new Entity("phonecall");
            Entity from = new Entity("activityparty");
            Entity to = new Entity("activityparty");

            from["partyid"] = new EntityReference("contact", contactId);
            to["partyid"] = new EntityReference("systemuser", systemUserId);
            phonecall.Attributes["from"] = new Entity[] { from };
            phonecall.Attributes["to"] = new Entity[] { to };

On Create request its giving below error:-
An error occurred while validating input parameters: Microsoft.OData.ODataException: Does not support untyped value in non-open type.

Am i doing anything wrong or is it not supported with this?

Thanks

**Comment by MattB-msft** [comment]
that is how its supposed to work.. we are looking at it now.
thanks for reporting !

**Comment by MattB-msft** [comment]
@vanita1012 
wanted to update you on this... 
we have this working now in our internal build and will be posting it in the near future. 

it has opened a number of new error types from our service that we are taking the opportunity to accommodate before posting the update.   the idea here is to give you guidance on what is wrong should the server deem something is incorrect with the Activity Party segment. 

thanks !
