### ISSUE TITLE
Microsoft.PowerPlatform.Cds.Client.Utils.CdsClientOperationException: The user with SystemUserId=6fc9a520-xx-xx-xxb1 in OrganizationContext=xx is disabled

### ISSUE THREAD

**Issue by V4A001** [microsoft/PowerPlatform-CdsServiceClient#71]
I use Azure Keyvault to pass my clientsecret and clientid. Upon insert I get an error. 
`Microsoft.PowerPlatform.Cds.Client.Utils.CdsClientOperationException: The user with SystemUserId=6fc9a520-xx-xx-xxb1 in OrganizationContext=xx is disabled
 ---> Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.PowerPlatform.Cds.Client.CdsConnectionService.ExecuteHttpRequestAsync(String uri, HttpMethod method, String body, Dictionary`2 customHeaders, CancellationToken cancellationToken, CdsTraceLogger logSink, Nullable`1 requestTrackingId, String contentType, Nullable`1 sessionTrackingId, Boolean suppressDebugMessage, HttpClient providedHttpClient)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_WebExecute(String queryString, String body, HttpMethod method, Dictionary`2 customHeaders, String contentType, String errorStringCheck, Guid requestTrackingId)
   --- End of inner exception stack trace ---
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.Create(Entity entity)`

When I look into my application insights log I see that in between a lot of operations with the same clientid, this error is thrown by the cdsclient. However, I checked and this SystemUserId is not my clientid. Can something go wrong in the cloning process? I will ask the IT guys to look if this SystemUserId is part of the AzureAD. But it is strange as the keys are only loaded at startup.

I looked at the Clone() but did not find anything. I do use early bounding (strong typed generated class with entities), but I do not use it with cdsclient.

`        public static void AddCdsServiceClient(this IServiceCollection services, Action<CdsServiceClientOptions> configureOptions)
        {
            CdsServiceClientOptions cdsServiceClientOptions = new CdsServiceClientOptions();
            configureOptions(cdsServiceClientOptions);

            services.AddSingleton(sp =>
                new CdsServiceClientWrapper(
                    cdsServiceClientOptions,
                    sp.GetRequiredService<ILogger<CdsServiceClientWrapper>>(),
                    cdsServiceClientOptions.TraceLevel)
                );

            services.AddScoped<IOrganizationService, CdsServiceClient>(sp =>
                sp.GetService<CdsServiceClientWrapper>()._cdsServiceClient.Clone());

            if (cdsServiceClientOptions.IncludeOrganizationServiceContext)
            {
                services.AddScoped(sp =>
                    new OrganizationServiceContext(sp.GetService<IOrganizationService>()));
            }
        }`

**Comment by MattB-msft** [comment]
This is the Error: **The user with SystemUserId=6fc9a520-xx-xx-xxb1 in OrganizationContext=xx is disabled**
That will be the user ID that your application user is mapped too.  have you checked to see that it is not disabled?

**Comment by V4A001** [comment]
I understand. No code has been changed and functionality works fine. This SystemUserId must be a clientid which is not present in the app registrations, nor in the azure ad as user. So how can this error only happen on PowerPlatform-CdsServiceClient and not for the regular httpsclient and servicecontext calls just before and after this error?

**Comment by MattB-msft** [comment]
@V4A001,  so im clear on what your saying as the helpers your using are not our code.. 

You have created a connection string with authtype=ClientSecret? or are you using the constructor to create a Client\Secret based auth flow? 

The constructor is not throwing an error? 
 and is the CdsServiceClient.IsReady == true? 

is this happening on the first call your making? or is your client working properly, then you .clone it and it fails? 

thanks
MattB

**Comment by MattB-msft** [comment]
Going  to close this due to no Response... 
if its still an issue.. please do reopen and add some info 

thanks!

**Comment by V4A001** [comment]
Thank you. It turned out that in D365CE (CRM) the user who owns the process was disabled. This process sent out an email immediately upon record creation. So it was not the clientId/ clientSecret upon authentication. Initially I could not find the userid as it was not in the Active Directory. The userId shown was of the CRM user.

thank you for your kind help. Appreciated.
