### ISSUE TITLE
When is a release version expected?

### ISSUE THREAD

**Issue by davidop** [microsoft/PowerPlatform-CdsServiceClient#72]
We are currently migrating some Azure Functions from net462 to netcoreapp3.1 and we are very interested in this nuget package.

**Comment by MattB-msft** [comment]
We are still a ways away from a release version of this. 
Major updates pending: 
   We will soon be pushing updated to move to MSAL from AAD,
   Rename / renamespacing to new names for CDS
   Migration of more messages to underlying webAPI transport.

**Comment by davidop** [comment]
A shame.  Any suggestions for working with Azure Functions and CRM?

**Comment by jordimontana82** [comment]
Hi @MattB-msft , I understand there's lots of underlying changes and it's not a trivial task at all to estimate when a release version will be available, but do you have a general very high level estimate of when that could happen like (2021 Q1, 2022, ... ?) 
: )

Thanks!
