### ISSUE TITLE
Simple CRUD application sample

### ISSUE THREAD

**Issue by pierceboggan** [microsoft/PowerPlatform-CdsServiceClient#8]
Looking through the linked samples repository, it was tough for me to find any samples that used this new API.

A simple CRUD application would be super useful for understanding how to use this SDK. As a new user, I struggled to understand how to do the following:

* Get information for my connection string (where do I find this information in the Power Platform portal?) or otherwise authenticate. I would expect inline OAuth flow via an embedded browser window with MSAL.
* Understand how to query a list of entities, such as querying CDS over LINQ (get a list of all accounts). My expectation was a `GetItemsAsync<EntityType>()` or similar syntax.
* Understand how to create a new record. My expectation would syntax such as `CreateNewRecord<Account>(account)`, but it seems like I must manually pass a dictionary rather than using a C# model class.

These reflect my learnings as a completely new user to Common Data Service with previous C# experience as a developer. I'm happy to chat about my experience :)

**Comment by BetimBeja** [comment]
The `CdsServiceClient` is meant to be the replacement of [CrmServiceClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient?view=dynamics-xrmtooling-ce-9) and apart from supporting fewer authentication flows and having a different namespace all the examples built for `CrmServiceClient` should work by substituting it with `CdsServiceClient`.
You can find a sample Dockerized ASP.NET Core application that uses the `CdsServiceClient` in the following repo https://github.com/albanian-xrm/CdsClient-Demo/commit/3250811ba824fd8b413780535982e64af5d3758a

**Comment by mathiasbl** [comment]
There's a login control provided by Microsoft to use in WPF applications. Any other type of application you would have to implement the oauth flow yourself.

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-xrm-tooling-common-login-control-client-applications

**Comment by MattB-msft** [comment]
This lib does not yet have public example of a UX client to auth.. that said nearly all of the CrmServiceClient samples directly translate, with the exception of the need for an example of offloading token acquire using the new pattern in this lib, called out in the release notes.
