### ISSUE TITLE
Getting exception System.FormatException: String '1965-05-07T00:00:00Z' was not recognized as a valid Edm.Date

### ISSUE THREAD

**Issue by mdocter** [microsoft/PowerPlatform-CdsServiceClient#80]
I'm unable to create a new entity with a Date/time field behavior set to 'Date only'.

![image](https://user-images.githubusercontent.com/796916/103000620-ac350c00-452b-11eb-8325-78bdfe7ed24b.png)

The following error occurs:

    An error occurred while validating input parameters: Microsoft.OData.ODataException: Cannot convert the literal '1965-05-07T00:00:00Z' to the expected type 'Edm.Date'. ---> System.FormatException: String '1965-05-07T00:00:00Z' was not recognized as a valid Edm.Date. 

The oData Edm.Date format should be '1965-05-07' (so without the time and timezone part).

Currently the `Utils.toExpandoObject`-method 

https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/710f307599d7c4b8556b730e477f54304ceeb1db/src/GeneralTools/CDSClient/Client/Utils/Utils.cs#L323

serializes all DateTime values with time and timezone data. See:

https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/710f307599d7c4b8556b730e477f54304ceeb1db/src/GeneralTools/CDSClient/Client/Utils/Utils.cs#L388

but this line should check the attribute metadata to see if it should return a date only string value.

Hope this helps. Currently I have to workaround this error with a new field which does support the time part.

**Comment by MattB-msft** [comment]
Thanks for your feedback here,  
We have fixed this and will be in the next drop.

**Comment by mdocter** [comment]
Thanks Matt! Great news!
