### ISSUE TITLE
The solution does not compile

### ISSUE THREAD

**Issue by davidnmbond** [microsoft/PowerPlatform-CdsServiceClient#82]
A fresh checkout of the solution does not compile, as it references Microsoft-internal nuget repositories.

For example:

    <PackageReference Include="Microsoft.Dynamics.Sdk.Messages.Internal" Version="$(PackageVersion_CDSServerNuget)" />

I'm keen to contribute to this project, but little can be done until these internal nugets are published.

**Comment by MattB-msft** [comment]
Could you give us a bit more info on the compile failures your seeing? we do have a compile test and tests that check that normally as part of our build.

**Comment by MattB-msft** [comment]
Closing due to no feedback.

**Comment by davidnmbond** [comment]
Check out on a machine not connected to the Microsoft network. compile. observe compile failure.

**Comment by MattB-msft** [comment]
yes.. this is currently intended... we also call that out explicitly in the readme on the home page. 
This is done to prevent folks from cross compiling Cds Clients and CdsPlugins, which is supported for the full framework version of our SDK Clients,

Currently our server does not support .net core Plugins, thus the supporting libs are not published publicly.
