### ISSUE TITLE
OAuth error - 0.3.6-Alpha

### ISSUE THREAD

**Issue by rajyraman** [microsoft/PowerPlatform-CdsServiceClient#85]
I was trying out OAuth with the latest alpha version. The login window opens up, I can signin and I get a message that the window can be closed after successful signin with MFA. But, when I try to use the client, I get the exception below. Related to 
#83.

```json
{
    "error": "invalid_grant",
    "error_description": "AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000007-0000-0000-c000-000000000000'.\r\nTrace ID: 345786f0-9348-4c60-ba09-cb711f4c2b00\r\nCorrelation ID: 57100496-06ce-4640-8e69-d9221e051756\r\nTimestamp: 2021-01-15 18:54:14Z",
    "error_codes": [50076],
    "timestamp": "2021-01-15 18:54:14Z",
    "trace_id": "345786f0-9348-4c60-ba09-cb711f4c2b00",
    "correlation_id": "57100496-06ce-4640-8e69-d9221e051756",
    "error_uri": "https://login.microsoftonline.com/error?code=50076",
    "suberror": "basic_action"
}
```

![image](https://user-images.githubusercontent.com/5035266/104767622-93351900-57c0-11eb-9123-a18c66326a6c.png)

**Comment by MattB-msft** [comment]
Can you provide the connection string you used and the host platform/.net version?

**Comment by rajyraman** [comment]
Hi @MattB-msft - I used the constructor (see screenshot) which has appid and reply url.

**Comment by rajyraman** [comment]
I ran the code on .NET 5, Win10.

**Comment by rajyraman** [comment]
I tried it now. I am no longer getting this error. Not sure what changed.

**Comment by MattB-msft** [comment]
@rajyraman did it just start working? and then fail when you call CurrentAccessToken? or did you change your app registration?

**Comment by rajyraman** [comment]
It probably was always working. It fails only when I access CurrentAccessToken property.

**Comment by MattB-msft** [comment]
Odd..  internally that method is used anytime a connection is executed. 
We will take a look and see if we can repro..
so to confirm.

you using .net 5, win10, attempting user non-interactive auth, 
correct?

**Comment by rajyraman** [comment]
@MattB-msft - This happens when I have password value on a OAuth connection string or use the constructor, which is my error. Since it is OAuth I don't need to mention the password. Once I remove the password, it works fine.
