### ISSUE TITLE
Error: Unsupported Connection request

### ISSUE THREAD

**Issue by julian-westermann** [microsoft/PowerPlatform-CdsServiceClient#86]
I understand from #83 , that OAuth is a supported authentication type of this lib?
Because I get the error `Unsupported Connection request` from `CdsServiceClient` when using the following connection string:

`$"AuthType=OAuth;Url={orgUrl};Username={orgEmail};Password={orgPwd};AppId={orgAppId};RedirectUri=app://{orgAppId};LoginPrompt=Never";`

The `CrmServiceClient` works fine when using exactly the same connection string. Also using `https://localhost` as redirect uri as mentioned in #83 doesn´t solve this issue. Neither does leaving out the password in the connection string as mentioned in #85.

Is the error, one that comes back from the server (misconfiguration?) or is this error created within the `CdsServiceClient`?

I want to use `CdsServiceClient` to establish a connection to a dynamics 365 online tenant within a .net core 3.1 azure function.

**Comment by MattB-msft** [comment]
so a few things. 
1) This area of auth is buggy right now in our implementation of MSAL,  ( CrmServiceClient uses ADAL.net ) so there are few issues where the roll over to MFA is not working correctly. 
2) the connection flow your using there is known to be working and is in our test matrix.. so we cannot actually ship it if it does not work.  see [here](https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/72d87d439df619b3c861856eca8050c021a45c76/src/GeneralTools/CDSClient/UnitTests/CdsClient_Core_Tests/CdsServiceClientTests.cs#L541)
3) The reason you are seeing unsupported connection request is that the AAD is actively rejecting the auth type ( UID/PW flow).   why- A year or so back AAD began enforcing MFA ( multi factor authentication ) for user connections by default,  and thus, if you want to use that flow on a newer tenant, you need to either disabled MFA being required for all users access, or add an exception for the user ID you want to use for this flow to allow for auth w/out MFA.  
Is the tenant newer? and or does it have MFA required for normal user login?

In the scenario your working with there, its better to use a ClientID/Secret or a ClientID/Certificate flow to connect from your Azure Function.

thanks

**Comment by julian-westermann** [comment]
Thank you for your reply. So AAD handles requests using MSAL different then requests using ADAL. Is this correct?
I´m using a tenant created within CDX Experience so I figure it is a quite "new" (in terms of latest policies) tenant. However it does not require MFA when logging in. 
I will look into it until the end of the week and see if I can make it work according to your suggestions.

**Comment by julian-westermann** [comment]
Okay so now I tested and can say the following:

Using connection string with authtype ClientSecret works fine, thanks for that hint.
However OAuth still doesn´t work and MFA is not required when logging in, in fact it is even disabled because it is advertised as a premium feature.

**Comment by rajyraman** [comment]
@julian-westermann - I am using OAuth with MSFT's test AppId (51f81489-12ee-4a9e-aaae-a2591f45987d) on my LINQPad Driver with MFA and it works fine.

**Comment by julian-westermann** [comment]
Hey @rajyraman , thanks for your shout out. I tested with your connection string but had no luck. Might be a configuration issue. However the ClientSecret method is sufficient :)
