### ISSUE TITLE
Offline sync layer

### ISSUE THREAD

**Issue by pierceboggan** [microsoft/PowerPlatform-CdsServiceClient#9]
Does CDS have an offline-capable layer such as SQLite so that I can use my application while offline and sync back to CDS once I have access to internet?

**Comment by MattB-msft** [comment]
Offline is a pretty deep area Pierce,  
This area is a area of active development more so then what can be summarized here. 
A good place to start is here: https://powerapps.microsoft.com/en-us/blog/build-offline-apps-with-new-powerapps-capabilities/
