### ISSUE TITLE
Legacy branding (CDS) should be changed to Dataverse

### ISSUE THREAD

**Issue by dmakogon** [microsoft/PowerPlatform-CdsServiceClient#99]
I would suggest, at a minimum, adding a note to the [README ](https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/master/README.md) mentioning that this SDK targets Dataverse, and that CDS has been rebranded as such. There is currently no mention of Dataverse in the repo, aside from a [discussion topic](https://github.com/microsoft/PowerPlatform-CdsServiceClient/discussions/74).

**Comment by MattB-msft** [comment]
There is a larger rework in progress currently. 

We will be renamespacing the client in the next drop
